name: Netflix Movie Catalog Service Docker Image Build and Push

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ECR_REGISTRY: 700935310038.dkr.ecr.us-east-1.amazonaws.com
  AWS_ECR_USERNAME: AWS

  AWS_ECR_REPOSITORY: ai-agrima-netflixcatalog
  IMAGE_TAG: latest

jobs:
  
  Build:

    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        run: |
          echo ${{ secrets.AWS_ECR_PASSWORD }} | docker login --username ${{ env.AWS_ECR_USERNAME }}  --password-stdin ${{ env.AWS_ECR_REGISTRY }}

      - name: Build Image
        env:
          IMAGE_NAME: ${{ env.AWS_ECR_REGISTRY }}/${{ env.AWS_ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .

      - name: Push image to Amazon ECR
        env:
          IMAGE_NAME: ${{ env.AWS_ECR_REGISTRY }}/${{ env.AWS_ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
        run: |
          docker push ${{ env.IMAGE_NAME }}
